openapi: 3.0.0
info:
  title: Service API
  version: 0.0.1
  description: >

servers:
  - url: http://localhost:3002/api
paths:
  /todo:
    get:
      summary: Get a list of todo
      operationId: listCustomers
      tags:
        - todo
      responses:
        "200":
          description: A list of todo
          content:
            application/json:
              schema:
                type: object
                required:
                  - tasks
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/todo'
    post:
      summary: Create a new todo
      operationId: createCustomer
      tags:
        - todo
      requestBody:
        description: The todo to create
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
                  example: ストレッチ

      responses:
        "201":
          description: The created todo
          content:
            application/json:
              schema:
                type: object
                required:
                  - task
                properties:
                  task:
                    $ref: '#/components/schemas/todo'
  /todo/{id}:
    get:
      summary: Get a list of todo
      operationId: listCustomers
      tags:
        - todo
      parameters:
        - name: id
          in: path
          description: The ID of the todo to update
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: A list of todo
          content:
            application/json:
              schema:
                type: object
                required:
                  - task
                properties:
                  task:
                    $ref: '#/components/schemas/todo'
    put:
      summary: Update an existing todo
      operationId: updateCustomer
      tags:
        - todo
      parameters:
        - name: id
          in: path
          description: The ID of the todo to update
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        description: The todo to create
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
                  example: ストレッチ
                status:
                  type: string
                  example: DONE
      responses:
        "200":
          description: The deleted todo
          content:
            application/json:
              schema:
                type: object
                required:
                  - task
                properties:
                  task:
                    $ref: '#/components/schemas/todo'
    delete:
      summary: Update an existing todo
      operationId: updateCustomer
      tags:
        - todo
      parameters:
        - name: id
          in: path
          description: The ID of the todo to update
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: The updated todo
          content:
            application/json:
              schema:
                type: object
                required:
                  - task
                properties:
                  task:
                    $ref: '#/components/schemas/todo'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: Not Found
components:
  requestBodies:
    todo:
      description: A JSON object containing todo information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/todo' # contentもコンポーネントを使うことで簡潔になる
  schemas:
    todo:
      type: object
      required:
        - id
        - value
        - status
      properties:
        id:
          type: integer
          format: int64
          description: The task ID
          example: 1
        value:
          type: string
          description: TODO contents
          example: ランニング
        status:
          type: string
          description: status
          example: TODO
        createdAt:
          type: string
          example: "2023-04-12T10:24:25.568Z"
        updatedAt:
          type: string
          example: "2023-04-12T10:24:25.568Z"
